name: CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 8.3
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            codedmonkey/symfony:latest
            codedmonkey/symfony:8.3
      -
        name: Build and push 8.2
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_VERSION=8.2
          tags: |
            codedmonkey/symfony:8.2
      -
        name: Build and push 8.1
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_VERSION=8.1
          tags: codedmonkey/symfony:8.1
      -
        name: Build and push 8.0
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_VERSION=8.0
          tags: codedmonkey/symfony:8.0
      -
        name: Build and push 7.4
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_VERSION=7.4
          tags: codedmonkey/symfony:7.4
      -
        name: Build and push Nginx
        uses: docker/build-push-action@v2
        with:
          context: nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            codedmonkey/symfony-nginx:latest
